name: Testlemon MCP Docker Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/testlemon-mcp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Log in to registry
      uses: docker/login-action@v3.1.0
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        platforms: linux/amd64, linux/arm64
        tags: |
          index.docker.io/${{ secrets.DOCKER_ORGANIZATION_NAME }}/testlemon-mcp:${{ github.sha }}
          index.docker.io/${{ secrets.DOCKER_ORGANIZATION_NAME }}/testlemon-mcp:latest
        file: ./src/testlemon-mcp/Dockerfile